version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sentinel-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password@123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: product-api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    container_name: product-api-service
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=SentinelAuthDb;User Id=sa;Password=Password@123;TrustServerCertificate=True;
      - Jwt__Key=VerySecretDefaultKeyForSentinelAuthThatMustBeLongEnoughForHmac256SecurityHeadersSecure
      - Jwt__Issuer=SentinelAuth
      - Jwt__Audience=SentinelAuthUsers
      - Jwt__DurationInMinutes=15
    depends_on:
      db:
        condition: service_healthy
